---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zz_muggle.
--- DateTime: 2024/10/21 16:34
---


-- 锁的key
local key = KEYS[1]
--当前线程标识
local threadId = ARGV[1]

local id = redis.call('get',key)

if(id == threadId) then
    return redis.call('del',key)
end
return 0